import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { ChangeEvent, useEffect, useState } from "react";
import * as esbuild from "esbuild-wasm";
import { useAppDispatch } from "@/hooks/useAppDispatch";
import {
  initializeEsbuild,
  selectInitializingEsbuild,
} from "@/features/transpiler/transpilerSlice";
import { useAppSelector } from "@/hooks/useAppSelector";

const Home = () => {
  const [code, setCode] = useState<string>("");
  const isInitializingEsbuild = useAppSelector(selectInitializingEsbuild);
  const dispatch = useAppDispatch();

  const onChange = (event: ChangeEvent<HTMLTextAreaElement>) => {
    setCode(event.target.value);
  };

  useEffect(() => {
    dispatch(initializeEsbuild());
  }, []);

  const transpile = async () => {
    const result = await esbuild.transform(code, { loader: "ts" });
    console.log(result.code);
  };

  return (
    <>
      <Head>
        <title>TS Transpiler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {isInitializingEsbuild && <h1>Loading</h1>}
        <textarea
          value={code}
          onChange={onChange}
          id="code"
          name="code"
          rows={12}
          className="mt-1 p-2 block w-full rounded-md border-2 border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
          placeholder="code"
        />
        <button
          type="button"
          onClick={transpile}
          className="text-white mt-2 bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 disabled:opacity-50 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2"
        >
          Transpile code
        </button>
      </main>
    </>
  );
};

export default Home;
